#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config nornal_border_color		"#282828"
bspc config focused_border_color	"#81A1C1"
bspc config urgent_border_color		"#88C0D0"
bspc config presel_border_color		"#8FBCBB"
bspc config presel_feedback_color	"#81A1C1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a google-chrome-stable desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating
# bspc rule -a Sxiv state=floating

sh ~/.config/polybar/launch.sh

# automatic change wallpaper every 10min
sh ~/.config/bspwm/wallpapers.sh

