theme = "ayu_mirage"

[editor]
true-color = true
cursorline = true
bufferline = "always"

[editor.statusline]
left = ["mode"]
center = ["file-name", "spinner", "diagnostics"]
right = ["selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
"A-q" = ":quit"
"A-w" = ":write"
"C-e" = "scroll_down"
"C-y" = "scroll_up"
"C-j" = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
"C-k" = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]

[keys.insert]
"C-e" = "goto_line_end_newline"
"C-a" = "goto_line_start"
"C-p" = "move_line_up"
"C-n" = "move_line_down"
"C-f" = "move_char_right"
"C-b" = "move_char_left"

[keys.select]

